---
openapi: '3.0.0'
info:
  title: only components
  version: 1.0.0
  description: Test spec for only components
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
tags:
  - name: default
    description: default API
paths: {}
components:
  schemas:
    Pet:
      description: Pet
      type: object
      required:
        - id
        - name
      properties:
        id:
          description: pet id
          type: integer
          format: int64
        kind:
          description: kind of pet
          type: string
          enum:
            - Dog
            - Cat
