name: Lint & Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
          cache: 'yarn'
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn example:generate
      - run: yarn lint
      - run: yarn test
      - run: yarn example:build
